var citys = [{
    "area_id": 1,
    "area_name": "北京市",
    "citys": [{
        "area_id": 2,
        "parent_id": 1,
        "area_name": "东城区"
    }, {
        "area_id": 3,
        "parent_id": 1,
        "area_name": "西城区"
    }, {
        "area_id": 4,
        "parent_id": 1,
        "area_name": "朝阳区"
    }, {
        "area_id": 5,
        "parent_id": 1,
        "area_name": "海淀区"
    }, {
        "area_id": 6,
        "parent_id": 1,
        "area_name": "丰台区"
    }, {
        "area_id": 7,
        "parent_id": 1,
        "area_name": "石景山区"
    }, {
        "area_id": 8,
        "parent_id": 1,
        "area_name": "门头沟区"
    }, {
        "area_id": 9,
        "parent_id": 1,
        "area_name": "房山区"
    }, {
        "area_id": 10,
        "parent_id": 1,
        "area_name": "通州区"
    }, {
        "area_id": 11,
        "parent_id": 1,
        "area_name": "顺义区"
    }, {
        "area_id": 12,
        "parent_id": 1,
        "area_name": "大兴区"
    }, {
        "area_id": 13,
        "parent_id": 1,
        "area_name": "昌平区"
    }, {
        "area_id": 14,
        "parent_id": 1,
        "area_name": "平谷区"
    }, {
        "area_id": 15,
        "parent_id": 1,
        "area_name": "怀柔区"
    }, {
        "area_id": 16,
        "parent_id": 1,
        "area_name": "密云县"
    }, {
        "area_id": 17,
        "parent_id": 1,
        "area_name": "延庆县"
    }]
}, {
    "area_id": 18,
    "area_name": "天津市",
    "citys": [{
        "area_id": 19,
        "parent_id": 18,
        "area_name": "河北区"
    }, {
        "area_id": 20,
        "parent_id": 18,
        "area_name": "南开区"
    }, {
        "area_id": 21,
        "parent_id": 18,
        "area_name": "河东区"
    }, {
        "area_id": 22,
        "parent_id": 18,
        "area_name": "和平区"
    }, {
        "area_id": 23,
        "parent_id": 18,
        "area_name": "河西区"
    }, {
        "area_id": 24,
        "parent_id": 18,
        "area_name": "西青区"
    }, {
        "area_id": 25,
        "parent_id": 18,
        "area_name": "红桥区"
    }, {
        "area_id": 26,
        "parent_id": 18,
        "area_name": "津南区"
    }, {
        "area_id": 27,
        "parent_id": 18,
        "area_name": "北辰区"
    }, {
        "area_id": 28,
        "parent_id": 18,
        "area_name": "东丽区"
    }, {
        "area_id": 29,
        "parent_id": 18,
        "area_name": "宝坻区"
    }, {
        "area_id": 30,
        "parent_id": 18,
        "area_name": "静海县"
    }, {
        "area_id": 31,
        "parent_id": 18,
        "area_name": "武清区"
    }, {
        "area_id": 32,
        "parent_id": 18,
        "area_name": "蓟县"
    }, {
        "area_id": 33,
        "parent_id": 18,
        "area_name": "宁河县"
    }, {
        "area_id": 34,
        "parent_id": 18,
        "area_name": "滨海新区"
    }, {
        "area_id": 480,
        "parent_id": 18,
        "area_name": "东郊区"
    }]
}, {
    "area_id": 35,
    "area_name": "上海市",
    "citys": [{
        "area_id": 36,
        "parent_id": 35,
        "area_name": "黄浦区"
    }, {
        "area_id": 37,
        "parent_id": 35,
        "area_name": "金山区"
    }, {
        "area_id": 38,
        "parent_id": 35,
        "area_name": "虹口区"
    }, {
        "area_id": 39,
        "parent_id": 35,
        "area_name": "闵行区"
    }, {
        "area_id": 40,
        "parent_id": 35,
        "area_name": "浦东新区"
    }, {
        "area_id": 41,
        "parent_id": 35,
        "area_name": "闸北区"
    }, {
        "area_id": 42,
        "parent_id": 35,
        "area_name": "长宁区"
    }, {
        "area_id": 43,
        "parent_id": 35,
        "area_name": "静安区"
    }, {
        "area_id": 44,
        "parent_id": 35,
        "area_name": "杨浦区"
    }, {
        "area_id": 45,
        "parent_id": 35,
        "area_name": "宝山区"
    }, {
        "area_id": 46,
        "parent_id": 35,
        "area_name": "普陀区"
    }, {
        "area_id": 47,
        "parent_id": 35,
        "area_name": "嘉定区"
    }, {
        "area_id": 48,
        "parent_id": 35,
        "area_name": "崇明县"
    }, {
        "area_id": 49,
        "parent_id": 35,
        "area_name": "奉贤区"
    }, {
        "area_id": 50,
        "parent_id": 35,
        "area_name": "松江区"
    }, {
        "area_id": 51,
        "parent_id": 35,
        "area_name": "青浦区"
    }, {
        "area_id": 52,
        "parent_id": 35,
        "area_name": "徐汇区"
    }, {
        "area_id": 479,
        "parent_id": 35,
        "area_name": "黄埔区"
    }]
}, {
    "area_id": 53,
    "area_name": "重庆市",
    "citys": [{
        "area_id": 54,
        "parent_id": 53,
        "area_name": "万州区"
    }, {
        "area_id": 55,
        "parent_id": 53,
        "area_name": "涪陵区"
    }, {
        "area_id": 56,
        "parent_id": 53,
        "area_name": "渝中区"
    }, {
        "area_id": 57,
        "parent_id": 53,
        "area_name": "大渡口区"
    }, {
        "area_id": 58,
        "parent_id": 53,
        "area_name": "江北区"
    }, {
        "area_id": 59,
        "parent_id": 53,
        "area_name": "沙坪坝区"
    }, {
        "area_id": 60,
        "parent_id": 53,
        "area_name": "九龙坡区"
    }, {
        "area_id": 61,
        "parent_id": 53,
        "area_name": "南岸区"
    }, {
        "area_id": 62,
        "parent_id": 53,
        "area_name": "北碚区"
    }, {
        "area_id": 63,
        "parent_id": 53,
        "area_name": "綦江区"
    }, {
        "area_id": 64,
        "parent_id": 53,
        "area_name": "大足区"
    }, {
        "area_id": 65,
        "parent_id": 53,
        "area_name": "渝北区"
    }, {
        "area_id": 66,
        "parent_id": 53,
        "area_name": "巴南区"
    }, {
        "area_id": 67,
        "parent_id": 53,
        "area_name": "黔江区"
    }, {
        "area_id": 68,
        "parent_id": 53,
        "area_name": "长寿区"
    }, {
        "area_id": 69,
        "parent_id": 53,
        "area_name": "江津区"
    }, {
        "area_id": 70,
        "parent_id": 53,
        "area_name": "合川区"
    }, {
        "area_id": 71,
        "parent_id": 53,
        "area_name": "永川区"
    }, {
        "area_id": 72,
        "parent_id": 53,
        "area_name": "南川区"
    }, {
        "area_id": 73,
        "parent_id": 53,
        "area_name": "璧山区"
    }, {
        "area_id": 74,
        "parent_id": 53,
        "area_name": "铜梁区"
    }, {
        "area_id": 75,
        "parent_id": 53,
        "area_name": "潼南县"
    }, {
        "area_id": 76,
        "parent_id": 53,
        "area_name": "荣昌县"
    }, {
        "area_id": 77,
        "parent_id": 53,
        "area_name": "梁平县"
    }, {
        "area_id": 78,
        "parent_id": 53,
        "area_name": "城口县"
    }, {
        "area_id": 79,
        "parent_id": 53,
        "area_name": "丰都县"
    }, {
        "area_id": 80,
        "parent_id": 53,
        "area_name": "垫江县"
    }, {
        "area_id": 81,
        "parent_id": 53,
        "area_name": "武隆县"
    }, {
        "area_id": 82,
        "parent_id": 53,
        "area_name": "忠县"
    }, {
        "area_id": 83,
        "parent_id": 53,
        "area_name": "开县"
    }, {
        "area_id": 84,
        "parent_id": 53,
        "area_name": "云阳县"
    }, {
        "area_id": 85,
        "parent_id": 53,
        "area_name": "奉节县"
    }, {
        "area_id": 86,
        "parent_id": 53,
        "area_name": "巫山县"
    }, {
        "area_id": 87,
        "parent_id": 53,
        "area_name": "巫溪县"
    }, {
        "area_id": 88,
        "parent_id": 53,
        "area_name": "彭水苗族土家族自治县"
    }, {
        "area_id": 89,
        "parent_id": 53,
        "area_name": "石柱土家族自治县"
    }, {
        "area_id": 90,
        "parent_id": 53,
        "area_name": "秀山土家族苗族自治县"
    }, {
        "area_id": 91,
        "parent_id": 53,
        "area_name": "酉阳土家族苗族自治县"
    }, {
        "area_id": 481,
        "parent_id": 53,
        "area_name": "万盛区"
    }, {
        "area_id": 482,
        "parent_id": 53,
        "area_name": "綦江县"
    }, {
        "area_id": 483,
        "parent_id": 53,
        "area_name": "璧山县"
    }, {
        "area_id": 484,
        "parent_id": 53,
        "area_name": "大足县"
    }, {
        "area_id": 485,
        "parent_id": 53,
        "area_name": "铜梁县"
    }, {
        "area_id": 486,
        "parent_id": 53,
        "area_name": "秀山县"
    }, {
        "area_id": 487,
        "parent_id": 53,
        "area_name": "西阳县"
    }, {
        "area_id": 488,
        "parent_id": 53,
        "area_name": "双桥区"
    }]
}, {
    "area_id": 92,
    "area_name": "河北省",
    "citys": [{
        "area_id": 93,
        "parent_id": 92,
        "area_name": "石家庄市"
    }, {
        "area_id": 94,
        "parent_id": 92,
        "area_name": "唐山市"
    }, {
        "area_id": 95,
        "parent_id": 92,
        "area_name": "邯郸市"
    }, {
        "area_id": 96,
        "parent_id": 92,
        "area_name": "保定市"
    }, {
        "area_id": 97,
        "parent_id": 92,
        "area_name": "张家口市"
    }, {
        "area_id": 98,
        "parent_id": 92,
        "area_name": "承德市"
    }, {
        "area_id": 99,
        "parent_id": 92,
        "area_name": "廊坊市"
    }, {
        "area_id": 100,
        "parent_id": 92,
        "area_name": "沧州市"
    }, {
        "area_id": 101,
        "parent_id": 92,
        "area_name": "衡水市"
    }, {
        "area_id": 102,
        "parent_id": 92,
        "area_name": "邢台市"
    }, {
        "area_id": 103,
        "parent_id": 92,
        "area_name": "秦皇岛市"
    }]
}, {
    "area_id": 104,
    "area_name": "山西省",
    "citys": [{
        "area_id": 105,
        "parent_id": 104,
        "area_name": "太原市"
    }, {
        "area_id": 106,
        "parent_id": 104,
        "area_name": "大同市"
    }, {
        "area_id": 107,
        "parent_id": 104,
        "area_name": "阳泉市"
    }, {
        "area_id": 108,
        "parent_id": 104,
        "area_name": "长治市"
    }, {
        "area_id": 109,
        "parent_id": 104,
        "area_name": "晋城市"
    }, {
        "area_id": 110,
        "parent_id": 104,
        "area_name": "朔州市"
    }, {
        "area_id": 111,
        "parent_id": 104,
        "area_name": "晋中市"
    }, {
        "area_id": 112,
        "parent_id": 104,
        "area_name": "运城市"
    }, {
        "area_id": 113,
        "parent_id": 104,
        "area_name": "忻州市"
    }, {
        "area_id": 114,
        "parent_id": 104,
        "area_name": "临汾市"
    }, {
        "area_id": 115,
        "parent_id": 104,
        "area_name": "吕梁市"
    }]
}, {
    "area_id": 116,
    "area_name": "辽宁省",
    "citys": [{
        "area_id": 117,
        "parent_id": 116,
        "area_name": "沈阳市"
    }, {
        "area_id": 118,
        "parent_id": 116,
        "area_name": "铁岭市"
    }, {
        "area_id": 119,
        "parent_id": 116,
        "area_name": "大连市"
    }, {
        "area_id": 120,
        "parent_id": 116,
        "area_name": "鞍山市"
    }, {
        "area_id": 121,
        "parent_id": 116,
        "area_name": "抚顺市"
    }, {
        "area_id": 122,
        "parent_id": 116,
        "area_name": "本溪市"
    }, {
        "area_id": 123,
        "parent_id": 116,
        "area_name": "丹东市"
    }, {
        "area_id": 124,
        "parent_id": 116,
        "area_name": "锦州市"
    }, {
        "area_id": 125,
        "parent_id": 116,
        "area_name": "营口市"
    }, {
        "area_id": 126,
        "parent_id": 116,
        "area_name": "阜新市"
    }, {
        "area_id": 127,
        "parent_id": 116,
        "area_name": "辽阳市"
    }, {
        "area_id": 128,
        "parent_id": 116,
        "area_name": "朝阳市"
    }, {
        "area_id": 129,
        "parent_id": 116,
        "area_name": "盘锦市"
    }, {
        "area_id": 130,
        "parent_id": 116,
        "area_name": "葫芦岛市"
    }]
}, {
    "area_id": 131,
    "area_name": "吉林省",
    "citys": [{
        "area_id": 132,
        "parent_id": 131,
        "area_name": "长春市"
    }, {
        "area_id": 133,
        "parent_id": 131,
        "area_name": "吉林市"
    }, {
        "area_id": 134,
        "parent_id": 131,
        "area_name": "延边朝鲜族自治州"
    }, {
        "area_id": 135,
        "parent_id": 131,
        "area_name": "四平市"
    }, {
        "area_id": 136,
        "parent_id": 131,
        "area_name": "通化市"
    }, {
        "area_id": 137,
        "parent_id": 131,
        "area_name": "白城市"
    }, {
        "area_id": 138,
        "parent_id": 131,
        "area_name": "辽源市"
    }, {
        "area_id": 139,
        "parent_id": 131,
        "area_name": "松原市"
    }, {
        "area_id": 140,
        "parent_id": 131,
        "area_name": "白山市"
    }]
}, {
    "area_id": 141,
    "area_name": "黑龙江省",
    "citys": [{
        "area_id": 142,
        "parent_id": 141,
        "area_name": "哈尔滨市"
    }, {
        "area_id": 143,
        "parent_id": 141,
        "area_name": "齐齐哈尔市"
    }, {
        "area_id": 144,
        "parent_id": 141,
        "area_name": "牡丹江市"
    }, {
        "area_id": 145,
        "parent_id": 141,
        "area_name": "佳木斯市"
    }, {
        "area_id": 146,
        "parent_id": 141,
        "area_name": "绥化市"
    }, {
        "area_id": 147,
        "parent_id": 141,
        "area_name": "黑河市"
    }, {
        "area_id": 148,
        "parent_id": 141,
        "area_name": "大兴安岭地区"
    }, {
        "area_id": 149,
        "parent_id": 141,
        "area_name": "伊春市"
    }, {
        "area_id": 150,
        "parent_id": 141,
        "area_name": "大庆市"
    }, {
        "area_id": 151,
        "parent_id": 141,
        "area_name": "七台河市"
    }, {
        "area_id": 152,
        "parent_id": 141,
        "area_name": "鸡西市"
    }, {
        "area_id": 153,
        "parent_id": 141,
        "area_name": "鹤岗市"
    }, {
        "area_id": 154,
        "parent_id": 141,
        "area_name": "双鸭山市"
    }]
}, {
    "area_id": 155,
    "area_name": "江苏省",
    "citys": [{
        "area_id": 156,
        "parent_id": 155,
        "area_name": "南京市"
    }, {
        "area_id": 157,
        "parent_id": 155,
        "area_name": "无锡市"
    }, {
        "area_id": 158,
        "parent_id": 155,
        "area_name": "镇江市"
    }, {
        "area_id": 159,
        "parent_id": 155,
        "area_name": "苏州市"
    }, {
        "area_id": 160,
        "parent_id": 155,
        "area_name": "南通市"
    }, {
        "area_id": 161,
        "parent_id": 155,
        "area_name": "扬州市"
    }, {
        "area_id": 162,
        "parent_id": 155,
        "area_name": "盐城市"
    }, {
        "area_id": 163,
        "parent_id": 155,
        "area_name": "徐州市"
    }, {
        "area_id": 164,
        "parent_id": 155,
        "area_name": "淮安市"
    }, {
        "area_id": 165,
        "parent_id": 155,
        "area_name": "连云港市"
    }, {
        "area_id": 166,
        "parent_id": 155,
        "area_name": "常州市"
    }, {
        "area_id": 167,
        "parent_id": 155,
        "area_name": "泰州市"
    }, {
        "area_id": 168,
        "parent_id": 155,
        "area_name": "宿迁市"
    }]
}, {
    "area_id": 169,
    "area_name": "浙江省",
    "citys": [{
        "area_id": 170,
        "parent_id": 169,
        "area_name": "杭州市"
    }, {
        "area_id": 171,
        "parent_id": 169,
        "area_name": "湖州市"
    }, {
        "area_id": 172,
        "parent_id": 169,
        "area_name": "嘉兴市"
    }, {
        "area_id": 173,
        "parent_id": 169,
        "area_name": "宁波市"
    }, {
        "area_id": 174,
        "parent_id": 169,
        "area_name": "绍兴市"
    }, {
        "area_id": 175,
        "parent_id": 169,
        "area_name": "台州市"
    }, {
        "area_id": 176,
        "parent_id": 169,
        "area_name": "温州市"
    }, {
        "area_id": 177,
        "parent_id": 169,
        "area_name": "丽水市"
    }, {
        "area_id": 178,
        "parent_id": 169,
        "area_name": "金华市"
    }, {
        "area_id": 179,
        "parent_id": 169,
        "area_name": "舟山市"
    }, {
        "area_id": 180,
        "parent_id": 169,
        "area_name": "衢州市"
    }]
}, {
    "area_id": 181,
    "area_name": "安徽省",
    "citys": [{
        "area_id": 182,
        "parent_id": 181,
        "area_name": "合肥市"
    }, {
        "area_id": 183,
        "parent_id": 181,
        "area_name": "滁州市"
    }, {
        "area_id": 184,
        "parent_id": 181,
        "area_name": "蚌埠市"
    }, {
        "area_id": 185,
        "parent_id": 181,
        "area_name": "芜湖市"
    }, {
        "area_id": 186,
        "parent_id": 181,
        "area_name": "淮南市"
    }, {
        "area_id": 187,
        "parent_id": 181,
        "area_name": "马鞍山市"
    }, {
        "area_id": 188,
        "parent_id": 181,
        "area_name": "安庆市"
    }, {
        "area_id": 189,
        "parent_id": 181,
        "area_name": "宿州市"
    }, {
        "area_id": 190,
        "parent_id": 181,
        "area_name": "阜阳市"
    }, {
        "area_id": 191,
        "parent_id": 181,
        "area_name": "亳州市"
    }, {
        "area_id": 192,
        "parent_id": 181,
        "area_name": "黄山市"
    }, {
        "area_id": 193,
        "parent_id": 181,
        "area_name": "淮北市"
    }, {
        "area_id": 194,
        "parent_id": 181,
        "area_name": "铜陵市"
    }, {
        "area_id": 195,
        "parent_id": 181,
        "area_name": "宣城市"
    }, {
        "area_id": 196,
        "parent_id": 181,
        "area_name": "六安市"
    }, {
        "area_id": 197,
        "parent_id": 181,
        "area_name": "池州市"
    }, {
        "area_id": 477,
        "parent_id": 181,
        "area_name": "巢湖市"
    }, {
        "area_id": 478,
        "parent_id": 181,
        "area_name": "芜湖市市"
    }]
}, {
    "area_id": 198,
    "area_name": "福建省",
    "citys": [{
        "area_id": 199,
        "parent_id": 198,
        "area_name": "福州市"
    }, {
        "area_id": 200,
        "parent_id": 198,
        "area_name": "厦门市"
    }, {
        "area_id": 201,
        "parent_id": 198,
        "area_name": "宁德市"
    }, {
        "area_id": 202,
        "parent_id": 198,
        "area_name": "莆田市"
    }, {
        "area_id": 203,
        "parent_id": 198,
        "area_name": "泉州市"
    }, {
        "area_id": 204,
        "parent_id": 198,
        "area_name": "漳州市"
    }, {
        "area_id": 205,
        "parent_id": 198,
        "area_name": "龙岩市"
    }, {
        "area_id": 206,
        "parent_id": 198,
        "area_name": "三明市"
    }, {
        "area_id": 207,
        "parent_id": 198,
        "area_name": "南平市"
    }]
}, {
    "area_id": 208,
    "area_name": "江西省",
    "citys": [{
        "area_id": 209,
        "parent_id": 208,
        "area_name": "南昌市"
    }, {
        "area_id": 210,
        "parent_id": 208,
        "area_name": "鹰潭市"
    }, {
        "area_id": 211,
        "parent_id": 208,
        "area_name": "新余市"
    }, {
        "area_id": 212,
        "parent_id": 208,
        "area_name": "九江市"
    }, {
        "area_id": 213,
        "parent_id": 208,
        "area_name": "上饶市"
    }, {
        "area_id": 214,
        "parent_id": 208,
        "area_name": "抚州市"
    }, {
        "area_id": 215,
        "parent_id": 208,
        "area_name": "赣州市"
    }, {
        "area_id": 216,
        "parent_id": 208,
        "area_name": "宜春市"
    }, {
        "area_id": 217,
        "parent_id": 208,
        "area_name": "吉安市"
    }, {
        "area_id": 218,
        "parent_id": 208,
        "area_name": "景德镇市"
    }, {
        "area_id": 219,
        "parent_id": 208,
        "area_name": "萍乡市"
    }]
}, {
    "area_id": 220,
    "area_name": "山东省",
    "citys": [{
        "area_id": 221,
        "parent_id": 220,
        "area_name": "济南市"
    }, {
        "area_id": 222,
        "parent_id": 220,
        "area_name": "烟台市"
    }, {
        "area_id": 223,
        "parent_id": 220,
        "area_name": "菏泽市"
    }, {
        "area_id": 224,
        "parent_id": 220,
        "area_name": "青岛市"
    }, {
        "area_id": 225,
        "parent_id": 220,
        "area_name": "淄博市"
    }, {
        "area_id": 226,
        "parent_id": 220,
        "area_name": "德州市"
    }, {
        "area_id": 227,
        "parent_id": 220,
        "area_name": "潍坊市"
    }, {
        "area_id": 228,
        "parent_id": 220,
        "area_name": "济宁市"
    }, {
        "area_id": 229,
        "parent_id": 220,
        "area_name": "枣庄市"
    }, {
        "area_id": 230,
        "parent_id": 220,
        "area_name": "泰安市"
    }, {
        "area_id": 231,
        "parent_id": 220,
        "area_name": "临沂市"
    }, {
        "area_id": 232,
        "parent_id": 220,
        "area_name": "滨州市"
    }, {
        "area_id": 233,
        "parent_id": 220,
        "area_name": "东营市"
    }, {
        "area_id": 234,
        "parent_id": 220,
        "area_name": "威海市"
    }, {
        "area_id": 235,
        "parent_id": 220,
        "area_name": "日照市"
    }, {
        "area_id": 236,
        "parent_id": 220,
        "area_name": "莱芜市"
    }, {
        "area_id": 237,
        "parent_id": 220,
        "area_name": "聊城市"
    }]
}, {
    "area_id": 238,
    "area_name": "河南省",
    "citys": [{
        "area_id": 239,
        "parent_id": 238,
        "area_name": "郑州市"
    }, {
        "area_id": 240,
        "parent_id": 238,
        "area_name": "商丘市"
    }, {
        "area_id": 241,
        "parent_id": 238,
        "area_name": "安阳市"
    }, {
        "area_id": 242,
        "parent_id": 238,
        "area_name": "新乡市"
    }, {
        "area_id": 243,
        "parent_id": 238,
        "area_name": "许昌市"
    }, {
        "area_id": 244,
        "parent_id": 238,
        "area_name": "平顶山市"
    }, {
        "area_id": 245,
        "parent_id": 238,
        "area_name": "周口市"
    }, {
        "area_id": 246,
        "parent_id": 238,
        "area_name": "漯河市"
    }, {
        "area_id": 247,
        "parent_id": 238,
        "area_name": "驻马店市"
    }, {
        "area_id": 248,
        "parent_id": 238,
        "area_name": "信阳市"
    }, {
        "area_id": 249,
        "parent_id": 238,
        "area_name": "南阳市"
    }, {
        "area_id": 250,
        "parent_id": 238,
        "area_name": "开封市"
    }, {
        "area_id": 251,
        "parent_id": 238,
        "area_name": "洛阳市"
    }, {
        "area_id": 252,
        "parent_id": 238,
        "area_name": "焦作市"
    }, {
        "area_id": 253,
        "parent_id": 238,
        "area_name": "济源市"
    }, {
        "area_id": 254,
        "parent_id": 238,
        "area_name": "鹤壁市"
    }, {
        "area_id": 255,
        "parent_id": 238,
        "area_name": "濮阳市"
    }, {
        "area_id": 256,
        "parent_id": 238,
        "area_name": "三门峡市"
    }]
}, {
    "area_id": 257,
    "area_name": "湖北省",
    "citys": [{
        "area_id": 258,
        "parent_id": 257,
        "area_name": "武汉市"
    }, {
        "area_id": 259,
        "parent_id": 257,
        "area_name": "襄阳市"
    }, {
        "area_id": 260,
        "parent_id": 257,
        "area_name": "鄂州市"
    }, {
        "area_id": 261,
        "parent_id": 257,
        "area_name": "孝感市"
    }, {
        "area_id": 262,
        "parent_id": 257,
        "area_name": "黄冈市"
    }, {
        "area_id": 263,
        "parent_id": 257,
        "area_name": "黄石市"
    }, {
        "area_id": 264,
        "parent_id": 257,
        "area_name": "咸宁市"
    }, {
        "area_id": 265,
        "parent_id": 257,
        "area_name": "荆州市"
    }, {
        "area_id": 266,
        "parent_id": 257,
        "area_name": "宜昌市"
    }, {
        "area_id": 267,
        "parent_id": 257,
        "area_name": "恩施土家族苗族自治州"
    }, {
        "area_id": 268,
        "parent_id": 257,
        "area_name": "十堰市"
    }, {
        "area_id": 269,
        "parent_id": 257,
        "area_name": "随州市"
    }, {
        "area_id": 270,
        "parent_id": 257,
        "area_name": "荆门市"
    }, {
        "area_id": 271,
        "parent_id": 257,
        "area_name": "天门市"
    }, {
        "area_id": 272,
        "parent_id": 257,
        "area_name": "潜江市"
    }, {
        "area_id": 273,
        "parent_id": 257,
        "area_name": "仙桃市"
    }, {
        "area_id": 274,
        "parent_id": 257,
        "area_name": "神农架林区"
    }]
}, {
    "area_id": 275,
    "area_name": "湖南省",
    "citys": [{
        "area_id": 276,
        "parent_id": 275,
        "area_name": "长沙市"
    }, {
        "area_id": 277,
        "parent_id": 275,
        "area_name": "岳阳市"
    }, {
        "area_id": 278,
        "parent_id": 275,
        "area_name": "湘潭市"
    }, {
        "area_id": 279,
        "parent_id": 275,
        "area_name": "株洲市"
    }, {
        "area_id": 280,
        "parent_id": 275,
        "area_name": "衡阳市"
    }, {
        "area_id": 281,
        "parent_id": 275,
        "area_name": "郴州市"
    }, {
        "area_id": 282,
        "parent_id": 275,
        "area_name": "常德市"
    }, {
        "area_id": 283,
        "parent_id": 275,
        "area_name": "益阳市"
    }, {
        "area_id": 284,
        "parent_id": 275,
        "area_name": "娄底市"
    }, {
        "area_id": 285,
        "parent_id": 275,
        "area_name": "邵阳市"
    }, {
        "area_id": 286,
        "parent_id": 275,
        "area_name": "湘西土家族苗族自治州"
    }, {
        "area_id": 287,
        "parent_id": 275,
        "area_name": "张家界市"
    }, {
        "area_id": 288,
        "parent_id": 275,
        "area_name": "怀化市"
    }, {
        "area_id": 289,
        "parent_id": 275,
        "area_name": "永州市"
    }]
}, {
    "area_id": 290,
    "area_name": "广东省",
    "citys": [{
        "area_id": 291,
        "parent_id": 290,
        "area_name": "广州市"
    }, {
        "area_id": 292,
        "parent_id": 290,
        "area_name": "江门市"
    }, {
        "area_id": 293,
        "parent_id": 290,
        "area_name": "韶关市"
    }, {
        "area_id": 294,
        "parent_id": 290,
        "area_name": "惠州市"
    }, {
        "area_id": 295,
        "parent_id": 290,
        "area_name": "梅州市"
    }, {
        "area_id": 296,
        "parent_id": 290,
        "area_name": "汕头市"
    }, {
        "area_id": 297,
        "parent_id": 290,
        "area_name": "深圳市"
    }, {
        "area_id": 298,
        "parent_id": 290,
        "area_name": "珠海市"
    }, {
        "area_id": 299,
        "parent_id": 290,
        "area_name": "佛山市"
    }, {
        "area_id": 300,
        "parent_id": 290,
        "area_name": "肇庆市"
    }, {
        "area_id": 301,
        "parent_id": 290,
        "area_name": "湛江市"
    }, {
        "area_id": 302,
        "parent_id": 290,
        "area_name": "中山市"
    }, {
        "area_id": 303,
        "parent_id": 290,
        "area_name": "河源市"
    }, {
        "area_id": 304,
        "parent_id": 290,
        "area_name": "清远市"
    }, {
        "area_id": 305,
        "parent_id": 290,
        "area_name": "云浮市"
    }, {
        "area_id": 306,
        "parent_id": 290,
        "area_name": "潮州市"
    }, {
        "area_id": 307,
        "parent_id": 290,
        "area_name": "汕尾市"
    }, {
        "area_id": 308,
        "parent_id": 290,
        "area_name": "阳江市"
    }, {
        "area_id": 309,
        "parent_id": 290,
        "area_name": "揭阳市"
    }, {
        "area_id": 310,
        "parent_id": 290,
        "area_name": "茂名市"
    }, {
        "area_id": 311,
        "parent_id": 290,
        "area_name": "东莞市"
    }]
}, {
    "area_id": 312,
    "area_name": "四川省",
    "citys": [{
        "area_id": 313,
        "parent_id": 312,
        "area_name": "成都市"
    }, {
        "area_id": 314,
        "parent_id": 312,
        "area_name": "攀枝花市"
    }, {
        "area_id": 315,
        "parent_id": 312,
        "area_name": "自贡市"
    }, {
        "area_id": 316,
        "parent_id": 312,
        "area_name": "绵阳市"
    }, {
        "area_id": 317,
        "parent_id": 312,
        "area_name": "南充市"
    }, {
        "area_id": 318,
        "parent_id": 312,
        "area_name": "达州市"
    }, {
        "area_id": 319,
        "parent_id": 312,
        "area_name": "遂宁市"
    }, {
        "area_id": 320,
        "parent_id": 312,
        "area_name": "广安市"
    }, {
        "area_id": 321,
        "parent_id": 312,
        "area_name": "巴中市"
    }, {
        "area_id": 322,
        "parent_id": 312,
        "area_name": "泸州市"
    }, {
        "area_id": 323,
        "parent_id": 312,
        "area_name": "宜宾市"
    }, {
        "area_id": 324,
        "parent_id": 312,
        "area_name": "内江市"
    }, {
        "area_id": 325,
        "parent_id": 312,
        "area_name": "资阳市"
    }, {
        "area_id": 326,
        "parent_id": 312,
        "area_name": "乐山市"
    }, {
        "area_id": 327,
        "parent_id": 312,
        "area_name": "眉山市"
    }, {
        "area_id": 328,
        "parent_id": 312,
        "area_name": "凉山彝族自治州"
    }, {
        "area_id": 329,
        "parent_id": 312,
        "area_name": "雅安市"
    }, {
        "area_id": 330,
        "parent_id": 312,
        "area_name": "甘孜藏族自治州"
    }, {
        "area_id": 331,
        "parent_id": 312,
        "area_name": "阿坝藏族羌族自治州"
    }, {
        "area_id": 332,
        "parent_id": 312,
        "area_name": "德阳市"
    }, {
        "area_id": 333,
        "parent_id": 312,
        "area_name": "广元市"
    }]
}, {
    "area_id": 334,
    "area_name": "贵州省",
    "citys": [{
        "area_id": 335,
        "parent_id": 334,
        "area_name": "贵阳市"
    }, {
        "area_id": 336,
        "parent_id": 334,
        "area_name": "遵义市"
    }, {
        "area_id": 337,
        "parent_id": 334,
        "area_name": "安顺市"
    }, {
        "area_id": 338,
        "parent_id": 334,
        "area_name": "黔南布依族苗族自治州"
    }, {
        "area_id": 339,
        "parent_id": 334,
        "area_name": "黔东南苗族侗族自治州"
    }, {
        "area_id": 340,
        "parent_id": 334,
        "area_name": "铜仁地区"
    }, {
        "area_id": 341,
        "parent_id": 334,
        "area_name": "毕节地区"
    }, {
        "area_id": 342,
        "parent_id": 334,
        "area_name": "六盘水市"
    }, {
        "area_id": 343,
        "parent_id": 334,
        "area_name": "黔西南布依族苗族自治州"
    }]
}, {
    "area_id": 344,
    "area_name": "云南省",
    "citys": [{
        "area_id": 345,
        "parent_id": 344,
        "area_name": "昆明市"
    }, {
        "area_id": 346,
        "parent_id": 344,
        "area_name": "西双版纳傣族自治州"
    }, {
        "area_id": 347,
        "parent_id": 344,
        "area_name": "德宏傣族景颇族自治州"
    }, {
        "area_id": 348,
        "parent_id": 344,
        "area_name": "昭通市"
    }, {
        "area_id": 349,
        "parent_id": 344,
        "area_name": "大理白族自治州"
    }, {
        "area_id": 350,
        "parent_id": 344,
        "area_name": "红河哈尼族彝族自治州"
    }, {
        "area_id": 351,
        "parent_id": 344,
        "area_name": "曲靖市"
    }, {
        "area_id": 352,
        "parent_id": 344,
        "area_name": "保山市"
    }, {
        "area_id": 353,
        "parent_id": 344,
        "area_name": "文山壮族苗族自治州"
    }, {
        "area_id": 354,
        "parent_id": 344,
        "area_name": "玉溪市"
    }, {
        "area_id": 355,
        "parent_id": 344,
        "area_name": "楚雄彝族自治州"
    }, {
        "area_id": 356,
        "parent_id": 344,
        "area_name": "普洱市"
    }, {
        "area_id": 357,
        "parent_id": 344,
        "area_name": "临沧市"
    }, {
        "area_id": 358,
        "parent_id": 344,
        "area_name": "怒江傈僳族自治州"
    }, {
        "area_id": 359,
        "parent_id": 344,
        "area_name": "迪庆藏族自治州"
    }, {
        "area_id": 360,
        "parent_id": 344,
        "area_name": "丽江市"
    }]
}, {
    "area_id": 361,
    "area_name": "陕西省",
    "citys": [{
        "area_id": 362,
        "parent_id": 361,
        "area_name": "西安市"
    }, {
        "area_id": 363,
        "parent_id": 361,
        "area_name": "咸阳市"
    }, {
        "area_id": 364,
        "parent_id": 361,
        "area_name": "延安市"
    }, {
        "area_id": 365,
        "parent_id": 361,
        "area_name": "榆林市"
    }, {
        "area_id": 366,
        "parent_id": 361,
        "area_name": "渭南市"
    }, {
        "area_id": 367,
        "parent_id": 361,
        "area_name": "商洛市"
    }, {
        "area_id": 368,
        "parent_id": 361,
        "area_name": "安康市"
    }, {
        "area_id": 369,
        "parent_id": 361,
        "area_name": "汉中市"
    }, {
        "area_id": 370,
        "parent_id": 361,
        "area_name": "宝鸡市"
    }, {
        "area_id": 371,
        "parent_id": 361,
        "area_name": "铜川市"
    }]
}, {
    "area_id": 372,
    "area_name": "甘肃省",
    "citys": [{
        "area_id": 373,
        "parent_id": 372,
        "area_name": "兰州市"
    }, {
        "area_id": 374,
        "parent_id": 372,
        "area_name": "金昌市"
    }, {
        "area_id": 375,
        "parent_id": 372,
        "area_name": "白银市 "
    }, {
        "area_id": 376,
        "parent_id": 372,
        "area_name": "天水市"
    }, {
        "area_id": 377,
        "parent_id": 372,
        "area_name": "嘉峪关市"
    }, {
        "area_id": 378,
        "parent_id": 372,
        "area_name": "武威市"
    }, {
        "area_id": 379,
        "parent_id": 372,
        "area_name": "张掖市 "
    }, {
        "area_id": 380,
        "parent_id": 372,
        "area_name": "平凉市"
    }, {
        "area_id": 381,
        "parent_id": 372,
        "area_name": "酒泉市"
    }, {
        "area_id": 382,
        "parent_id": 372,
        "area_name": "庆阳市 "
    }, {
        "area_id": 383,
        "parent_id": 372,
        "area_name": "定西市 "
    }, {
        "area_id": 384,
        "parent_id": 372,
        "area_name": "陇南市"
    }, {
        "area_id": 385,
        "parent_id": 372,
        "area_name": "临夏州"
    }, {
        "area_id": 386,
        "parent_id": 372,
        "area_name": "甘南州 "
    }, {
        "area_id": 491,
        "parent_id": 372,
        "area_name": "武威市 "
    }, {
        "area_id": 492,
        "parent_id": 372,
        "area_name": "酒泉市 "
    }]
}, {
    "area_id": 387,
    "area_name": "青海省",
    "citys": [{
        "area_id": 388,
        "parent_id": 387,
        "area_name": "西宁市"
    }, {
        "area_id": 389,
        "parent_id": 387,
        "area_name": "海东市"
    }, {
        "area_id": 390,
        "parent_id": 387,
        "area_name": "海北藏族自治州"
    }, {
        "area_id": 391,
        "parent_id": 387,
        "area_name": "黄南藏族自治州"
    }, {
        "area_id": 392,
        "parent_id": 387,
        "area_name": "海南藏族自治州"
    }, {
        "area_id": 393,
        "parent_id": 387,
        "area_name": "果洛藏族自治州"
    }, {
        "area_id": 394,
        "parent_id": 387,
        "area_name": "玉树藏族自治州"
    }, {
        "area_id": 395,
        "parent_id": 387,
        "area_name": "海西蒙古族藏族自治州"
    }, {
        "area_id": 494,
        "parent_id": 387,
        "area_name": "海东市 "
    }, {
        "area_id": 495,
        "parent_id": 387,
        "area_name": "海西蒙古族藏族自治州 "
    }]
}, {
    "area_id": 396,
    "area_name": "内蒙古自治区",
    "citys": [{
        "area_id": 397,
        "parent_id": 396,
        "area_name": "呼和浩特市"
    }, {
        "area_id": 398,
        "parent_id": 396,
        "area_name": "包头市"
    }, {
        "area_id": 399,
        "parent_id": 396,
        "area_name": "乌海市"
    }, {
        "area_id": 400,
        "parent_id": 396,
        "area_name": "赤峰市"
    }, {
        "area_id": 401,
        "parent_id": 396,
        "area_name": "通辽市"
    }, {
        "area_id": 402,
        "parent_id": 396,
        "area_name": "鄂尔多斯市 "
    }, {
        "area_id": 403,
        "parent_id": 396,
        "area_name": "呼伦贝尔市"
    }, {
        "area_id": 404,
        "parent_id": 396,
        "area_name": "巴彦淖尔市 "
    }, {
        "area_id": 405,
        "parent_id": 396,
        "area_name": "乌兰察布市 "
    }, {
        "area_id": 406,
        "parent_id": 396,
        "area_name": "锡林郭勒盟 "
    }, {
        "area_id": 407,
        "parent_id": 396,
        "area_name": "兴安盟 "
    }, {
        "area_id": 408,
        "parent_id": 396,
        "area_name": "阿拉善盟 "
    }, {
        "area_id": 489,
        "parent_id": 396,
        "area_name": "呼和浩特市 "
    }, {
        "area_id": 490,
        "parent_id": 396,
        "area_name": "乌兰察布市"
    }]
}, {
    "area_id": 409,
    "area_name": "广西壮族自治区",
    "citys": [{
        "area_id": 410,
        "parent_id": 409,
        "area_name": "南宁市"
    }, {
        "area_id": 411,
        "parent_id": 409,
        "area_name": "崇左市"
    }, {
        "area_id": 412,
        "parent_id": 409,
        "area_name": "防城港市"
    }, {
        "area_id": 413,
        "parent_id": 409,
        "area_name": "柳州市"
    }, {
        "area_id": 414,
        "parent_id": 409,
        "area_name": "来宾市"
    }, {
        "area_id": 415,
        "parent_id": 409,
        "area_name": "桂林市"
    }, {
        "area_id": 416,
        "parent_id": 409,
        "area_name": "梧州市"
    }, {
        "area_id": 417,
        "parent_id": 409,
        "area_name": "贺州市"
    }, {
        "area_id": 418,
        "parent_id": 409,
        "area_name": "玉林市"
    }, {
        "area_id": 419,
        "parent_id": 409,
        "area_name": "贵港市"
    }, {
        "area_id": 420,
        "parent_id": 409,
        "area_name": "百色市"
    }, {
        "area_id": 421,
        "parent_id": 409,
        "area_name": "钦州市"
    }, {
        "area_id": 422,
        "parent_id": 409,
        "area_name": "河池市"
    }, {
        "area_id": 423,
        "parent_id": 409,
        "area_name": "北海市"
    }]
}, {
    "area_id": 424,
    "area_name": "西藏自治区",
    "citys": [{
        "area_id": 425,
        "parent_id": 424,
        "area_name": "拉萨市"
    }, {
        "area_id": 426,
        "parent_id": 424,
        "area_name": "昌都市"
    }, {
        "area_id": 427,
        "parent_id": 424,
        "area_name": "山南地区 "
    }, {
        "area_id": 428,
        "parent_id": 424,
        "area_name": "日喀则市"
    }, {
        "area_id": 429,
        "parent_id": 424,
        "area_name": "林芝市"
    }, {
        "area_id": 430,
        "parent_id": 424,
        "area_name": "那曲地区"
    }, {
        "area_id": 431,
        "parent_id": 424,
        "area_name": "阿里地区"
    }, {
        "area_id": 513,
        "parent_id": 424,
        "area_name": "昌都地区 "
    }, {
        "area_id": 514,
        "parent_id": 424,
        "area_name": "日喀则市 "
    }]
}, {
    "area_id": 432,
    "area_name": "宁夏回族自治区",
    "citys": [{
        "area_id": 433,
        "parent_id": 432,
        "area_name": "银川市"
    }, {
        "area_id": 434,
        "parent_id": 432,
        "area_name": "石嘴山市"
    }, {
        "area_id": 435,
        "parent_id": 432,
        "area_name": "吴忠市 "
    }, {
        "area_id": 436,
        "parent_id": 432,
        "area_name": "固原市 "
    }, {
        "area_id": 437,
        "parent_id": 432,
        "area_name": "中卫市 "
    }, {
        "area_id": 493,
        "parent_id": 432,
        "area_name": "石嘴市 "
    }]
}, {
    "area_id": 438,
    "area_name": "新疆维吾尔自治区",
    "citys": [{
        "area_id": 439,
        "parent_id": 438,
        "area_name": "乌鲁木齐市"
    }, {
        "area_id": 440,
        "parent_id": 438,
        "area_name": "克拉玛依市"
    }, {
        "area_id": 441,
        "parent_id": 438,
        "area_name": "吐鲁番地区 "
    }, {
        "area_id": 442,
        "parent_id": 438,
        "area_name": "哈密地区"
    }, {
        "area_id": 443,
        "parent_id": 438,
        "area_name": "和田地区"
    }, {
        "area_id": 444,
        "parent_id": 438,
        "area_name": "阿克苏地区 "
    }, {
        "area_id": 445,
        "parent_id": 438,
        "area_name": "喀什地区 "
    }, {
        "area_id": 446,
        "parent_id": 438,
        "area_name": "克孜勒苏柯尔克孜自治州"
    }, {
        "area_id": 447,
        "parent_id": 438,
        "area_name": "巴音郭楞蒙古自治州"
    }, {
        "area_id": 448,
        "parent_id": 438,
        "area_name": "昌吉回族自治州 "
    }, {
        "area_id": 449,
        "parent_id": 438,
        "area_name": "博尔塔拉蒙古自治州"
    }, {
        "area_id": 450,
        "parent_id": 438,
        "area_name": "伊犁哈萨克自治州 "
    }, {
        "area_id": 451,
        "parent_id": 438,
        "area_name": "塔城地区"
    }, {
        "area_id": 452,
        "parent_id": 438,
        "area_name": "阿勒泰地区"
    }, {
        "area_id": 505,
        "parent_id": 438,
        "area_name": "哈密地区  "
    }, {
        "area_id": 506,
        "parent_id": 438,
        "area_name": "哈密地区 "
    }, {
        "area_id": 507,
        "parent_id": 438,
        "area_name": "阿克苏地区  "
    }, {
        "area_id": 508,
        "parent_id": 438,
        "area_name": "喀什地区  "
    }, {
        "area_id": 509,
        "parent_id": 438,
        "area_name": "巴音郭楞蒙古自治州 "
    }, {
        "area_id": 510,
        "parent_id": 438,
        "area_name": "博尔塔拉蒙古自治州 "
    }, {
        "area_id": 511,
        "parent_id": 438,
        "area_name": "塔城地区 "
    }, {
        "area_id": 512,
        "parent_id": 438,
        "area_name": "石河子市 "
    }]
}, {
    "area_id": 453,
    "area_name": "海南省",
    "citys": [{
        "area_id": 454,
        "parent_id": 453,
        "area_name": "海口市"
    }, {
        "area_id": 455,
        "parent_id": 453,
        "area_name": "三亚市"
    }, {
        "area_id": 456,
        "parent_id": 453,
        "area_name": "三沙市"
    }, {
        "area_id": 457,
        "parent_id": 453,
        "area_name": "五指山市"
    }, {
        "area_id": 458,
        "parent_id": 453,
        "area_name": "琼海市"
    }, {
        "area_id": 459,
        "parent_id": 453,
        "area_name": "儋州市"
    }, {
        "area_id": 460,
        "parent_id": 453,
        "area_name": "文昌市"
    }, {
        "area_id": 461,
        "parent_id": 453,
        "area_name": "万宁市"
    }, {
        "area_id": 462,
        "parent_id": 453,
        "area_name": "东方市"
    }, {
        "area_id": 463,
        "parent_id": 453,
        "area_name": "定安县"
    }, {
        "area_id": 464,
        "parent_id": 453,
        "area_name": "屯昌县"
    }, {
        "area_id": 465,
        "parent_id": 453,
        "area_name": "澄迈县"
    }, {
        "area_id": 466,
        "parent_id": 453,
        "area_name": "临高县"
    }, {
        "area_id": 467,
        "parent_id": 453,
        "area_name": "白沙黎族自治县"
    }, {
        "area_id": 468,
        "parent_id": 453,
        "area_name": "昌江黎族自治县"
    }, {
        "area_id": 469,
        "parent_id": 453,
        "area_name": "乐东黎族自治县"
    }, {
        "area_id": 470,
        "parent_id": 453,
        "area_name": "陵水黎族自治县"
    }, {
        "area_id": 471,
        "parent_id": 453,
        "area_name": "保亭黎族苗族自治县"
    }, {
        "area_id": 472,
        "parent_id": 453,
        "area_name": "琼中黎族苗族自治县"
    }, {
        "area_id": 496,
        "parent_id": 453,
        "area_name": "琼海市 "
    }, {
        "area_id": 497,
        "parent_id": 453,
        "area_name": "琼海市  "
    }, {
        "area_id": 498,
        "parent_id": 453,
        "area_name": "儋州市  "
    }, {
        "area_id": 499,
        "parent_id": 453,
        "area_name": "文昌市  "
    }, {
        "area_id": 500,
        "parent_id": 453,
        "area_name": "万宁市  "
    }, {
        "area_id": 501,
        "parent_id": 453,
        "area_name": "东方市  "
    }, {
        "area_id": 502,
        "parent_id": 453,
        "area_name": "白沙黎族自治县 "
    }, {
        "area_id": 503,
        "parent_id": 453,
        "area_name": "乐东黎族自治县 "
    }, {
        "area_id": 504,
        "parent_id": 453,
        "area_name": "琼中黎族苗族自治县 "
    }]
}, {
    "area_id": 473,
    "area_name": "港澳台",
    "citys": [{
        "area_id": 475,
        "parent_id": 473,
        "area_name": "港澳台"
    }]
}];
module.exports = citys;